<!DOCTYPE html>
<html lang="en">
<head>
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="./theme/stylesheet/style.min.css">

  <link rel="stylesheet" type="text/css" href="./theme/stylesheet/pygments.min.css">
  <link rel="stylesheet" type="text/css" href="./theme/stylesheet/font-awesome.min.css">


    <link href="Ganesh Kadam/feeds/all.atom.xml" type="application/atom+xml" rel="alternate" title=" Atom">



  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="" />

<meta name="author" content="Ganesh Kadam" />
<meta name="description" content="I was working on shell a script. Now that it was complete I need to send that script for review.So I started to work on this. Unfortunately I got the following error which took me almost took a day to resolve on my side. I decided not to ask ..." />
<meta name="keywords" content="Gerrit, Git">
<meta property="og:site_name" content=""/>
<meta property="og:title" content="Gerrit Issue"/>
<meta property="og:description" content="I was working on shell a script. Now that it was complete I need to send that script for review.So I started to work on this. Unfortunately I got the following error which took me almost took a day to resolve on my side. I decided not to ask ..."/>
<meta property="og:locale" content="en_US"/>
<meta property="og:url" content="./gerrit-issue.html"/>
<meta property="og:type" content="article"/>
<meta property="article:published_time" content="2016-04-26 00:00:00+05:30"/>
<meta property="article:modified_time" content=""/>
<meta property="article:author" content="./author/ganesh-kadam.html">
<meta property="article:section" content="TechNotes"/>
<meta property="article:tag" content="Gerrit"/>
<meta property="article:tag" content="Git"/>
<meta property="og:image" content="">
  <title> &ndash; Gerrit Issue</title>
</head>
<body>
  <aside>
    <div>
      <a href=".">
        <img src="./theme/img/profile.png" alt="" title="">
      </a>
      <h1><a href="."></a></h1>
      <p></p>
      <nav>
        <ul class="list">
        </ul>
      </nav>
      <ul class="social">
        <li><a class="sc-facebook" href="https://facebook.com/meganeshkadam" target="_blank"><i class="fa fa-facebook"></i></a></li>
        <li><a class="sc-twitter" href="https://twitter.com/meganeshkadam" target="_blank"><i class="fa fa-twitter"></i></a></li>
        <li><a class="sc-linkedin" href="https://in.linkedin.com/pub/ganesh-kadam/b0/746/192" target="_blank"><i class="fa fa-linkedin"></i></a></li>
        <li><a class="sc-github" href="https://github.com/meganeshkadam" target="_blank"><i class="fa fa-github"></i></a></li>
      </ul>
    </div>
  </aside>
  <main>

<article>
  <header>
    <h1 id="gerrit-issue">Gerrit Issue</h1>
    <p>Posted on Tue 26 April 2016 in <a href="./category/technotes.html">TechNotes</a></p>
  </header>
  <div>
    <p>I was working on shell a script. Now that it was complete I need to send that script for review.So I started to work on this.
Unfortunately I got the following error which took me almost took a day to resolve on my side. I decided not to ask my mentors until and unless  I am not able to rsolve this issue. This has been common issue amongst all of us interns!</p>
<pre class="literal-block">
[gkadam&#64;dhcp201-114 cert-openstack-scripts]$ git review -R
Could not connect to gerrit.
Enter your gerrit username: gkadam&#64;redhat.com
Trying again with ssh://gkadam&#64;redhat.com&#64;code.engineering.redhat.com:22/cert-openstack-scripts
&lt;traceback object at 0x7fa7a448cb00&gt;
We don't know where your gerrit is. Please manually create a remote
named &quot;gerrit&quot; and try again.
Could not connect to gerrit at ssh://gkadam&#64;redhat.com&#64;code.engineering.redhat.com:22/cert-openstack-acripts
Traceback (most recent call last):
File &quot;/usr/bin/git-review&quot;, line 11, in &lt;module&gt;
sys.exit(main())
File &quot;/usr/lib/python2.7/site-packages/git_review/cmd.py&quot;, line 1534, in main
sys.exit(e.EXIT_CODE)
AttributeError: 'GitReviewException' object has no attribute 'EXIT_CODE'
</pre>
<p>After going through lots of google serarches I realized that, the things that were going wrong are already mentioned in the error code that I was getting. Before this I made a very silly mistake of deleting the existing file in that directory from which I have to send the file for review. So just after knowing this issue, I copied the new script in to the same directory again. Then I renamed to it's earlier name and performed following steps :</p>
<ol class="arabic simple">
<li>Cloned the repository to new location :</li>
</ol>
<pre class="literal-block">
[gkadam&#64;dhcp201-114 ~]$ git clone ssh://gkadam&#64;code.engineering.redhat.com:22/cert-openstack-scripts
Cloning into 'cert-openstack-scripts'...
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
</pre>
<ol class="arabic simple" start="2">
<li>Added the remote repository as we can see in the above error!</li>
</ol>
<pre class="literal-block">
[gkadam&#64;dhcp201-114 cert-openstack-scripts]$ git remote add gerrit ssh://gkadam&#64;code.engineering.redhat.com:22/cert-openstack-scripts
</pre>
<ol class="arabic simple" start="3">
<li>Then did a git review after adding the script and commiting it in that dierctory :</li>
</ol>
<pre class="literal-block">
[gkadam&#64;dhcp201-114 cert-openstack-scripts]$ git review -R
Your change was committed before the commit hook was installed.
Amending the commit to add a gerrit change id.
remote: Processing changes: new: 1, refs: 1, done.
remote: (W) 9dedc09: commit subject &gt;65 characters; use shorter first paragraph
remote: (W) 9dedc09: too many commit message lines longer than 70 characters; manually wrap lines
remote:
remote: New Changes:
remote:https://code.engineering.redhat.com/gerrit/73014 Add user validation, and create functions : create_member,create_network and remote:
To ssh://gkadam&#64;code.engineering.redhat.com:22/cert-openstack-scripts
* [new branch]      HEAD -&gt; refs/publish/master
</pre>
<p>This was the workaround for my problem that I was facing.</p>
<p>Here is the link to the similar issue on git : <a class="reference external" href="https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/">Git remote HEAD Issue</a></p>

  </div>
  <div class="tag-cloud">
    <p>
      <a href="./tag/gerrit.html">Gerrit</a>
      <a href="./tag/git.html">Git</a>
    </p>
  </div>
</article>

    <footer>
        <p>&copy; Ganesh Kadam </p>
<p>Built using <a href="http://getpelican.com" target="_blank">Pelican</a> - <a href="https://github.com/alexandrevicenzi/flex" target="_blank">Flex</a> theme by <a href="http://alexandrevicenzi.com" target="_blank">Alexandre Vicenzi</a></p>    </footer>
  </main>





<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BlogPosting",
  "name": "Gerrit Issue",
  "headline": "Gerrit Issue",
  "datePublished": "2016-04-26 00:00:00+05:30",
  "dateModified": "",
  "author": {
    "@type": "Person",
    "name": "Ganesh Kadam",
    "url": "./author/ganesh-kadam.html"
  },
  "image": "{{ SITEURL }}/{{ THEME_STATIC_DIR }}/img/profile.png",
  "url": "./gerrit-issue.html",
  "description": "I was working on shell a script. Now that it was complete I need to send that script for review.So I started to work on this. Unfortunately I got the following error which took me almost took a day to resolve on my side. I decided not to ask ..."
}
</script></body>
</html>